/*
 * generated by Xtext 2.32.0
 */
package it.univaq.disim.usecase.statemachine.xtext.ide;


/**
 * Use this class to register ide components.
 */
public class StateMachineDslIdeModule extends AbstractStateMachineDslIdeModule {
}
