/*
 * generated by Xtext 2.32.0
 */
package it.univaq.disim.usecase.statemachine.xtext;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class StateMachineDslRuntimeModule extends AbstractStateMachineDslRuntimeModule {
}
