/*
 * generated by Xtext 2.32.0
 */
package it.univaq.disim.usecase.statemachine.xtext.ui.tests;

import com.google.inject.Injector;
import it.univaq.disim.usecase.statemachine.xtext.ui.internal.XtextActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class StateMachineDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return XtextActivator.getInstance().getInjector("it.univaq.disim.usecase.statemachine.xtext.StateMachineDsl");
	}

}
