/*
 * generated by Xtext 2.32.0
 */
package it.univaq.disim.usecase.statemachine.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class StateMachineDslUiModule extends AbstractStateMachineDslUiModule {

	public StateMachineDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
